<template>
  <div id="app" class="pt-12">
    <!-- Header -->
    <header class="fixed top-0 left-0 right-0 bg-white shadow-md z-50 bg-header-color">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <h1 class="text-2xl font-bold text-center text-white">Journal pour ma princesse 🦔</h1>
      </div>
    </header>

    <!-- Content -->
    <div class="pt-16 p-6">
      <JournalEntry v-for="entry in journalEntries" :key="entry.number" :title="entry.title" :content="entry.content"
        :entryNumber="entry.number" />
    </div>
  </div>
</template>

<script>
import JournalEntry from './components/JournalEntry.vue'

export default {
  name: 'App',
  components: {
    JournalEntry
  },
  data() {
    return {
      journalEntries: [
        { number: 1, title: '02 Juillet, 14h', content: "Ça fait bien 2/3 semaines que j'ai reçu la figurine qu'il manquait pour compléter ton Noël. Enfin pour être plus exacte la nouvelle figurine, l'autre a disparu pour d'obscures raisons à cause du marchand.<br/>Quoiqu'il en soit, tu commences à avoir l'habitude, faire les choses de manière basique, c'est à dire, faire un colis avec la figurine, avec un petit mot disant « tiens voilà le cadeau qu'il te manque, bisous », c'est pas mon truc, c'est trop simple...<br/>J'ai un certain niveau de qualité pour continuer à te draguer. Pour être honnête, aujourd'hui l'objectif c'est plus de simplement te draguer même ça c'est devenu mineur (comme toi au début quand tu mentais), l'objectif aujourd'hui, c'est de gagner ma place définitivement dans ton cœur. Je veux être ta première et dernière pensée de chaque journée.<br/>Alors comment faire ça quand l'énergumène qu'on souhaite est une petite conne, égocentrique, égoïste, qui passe son temps à râler et qui doute même dans notre existence ? Tout simplement en innovant.<br/>Alors voilà, j'ai déjà l'idée d'un colis, qui comportera au moins la figurine. <br/>Ah merde j'allais oublié, la partie sur le mariage. Euh Axelle, veux-tu m'épouser ? (Là t'es censée avoir la boîte en main et l'ouvrir).<br/>Blague à part (oui parce que hors de question de t'épouser sans avoir vérifié si t'as des cuisses VRAIMENT confortables), l'idée du cadeau, c'était de réunir mes deux passions, te draguer en étant romantique et te faire chier parce que c'est niais. Mais vu que t'aurais râlé si j'avais acheté quoique ce soit de vrai, j'ai été obligé de la faire en 3d... <br/>D'façon, si t'en veux une vraie un jour, drague moi à ton tour.<br/>Quoiqu'il en soit, il va être temps de clôturer cette première entrée à ce journal. Vu que j'ai que des idées galères, j'vais sûrement essayer de mettre ça en ligne sur un site que j'aurais fait, histoire que tu puisses tout consulter sans avoir 45 lettres chez toi...<br/>Y aura une entrée à chaque fois que je penserai à toi, jusqu'au jour de la réception je dirais ? Oh puis j'trouverai bien un moyen de rajouter des cadeaux aussi... Faut que je vois la taille du colis, et que j'équilibre par rapport à ton futur niveau de « Oh c'est trop et en plus y a pas de raison »." },
        { number: 2, title: '02 Juillet, 17h07', content: "Je me dois de revenir sur quelque chose. Je pourrais pas faire une entrée à chaque fois que je pense à toi... <br> Malheureusement, vu que tu fais parti de mes pensées chaque instant qui passe. Sûrement parce que tu es la seule et l'unique, mon rêve dans cette éternité. (Profite de te faire booster ton égo :)" },
        { number: 3, title: '03 Juillet, 2h30 ', content: "Pensée nocturne, pas des plus positives mais intéressante. Parfois je me dis que c’est bien inutile de mettre autant d’énergie. C’est bien le plus blessant chez toi, cette ignorance dont tu fais bien souvent preuve. Je regarde en arrière en me disant que si je n’avais persévéré, aujourd’hui je serais déjà oublié. Contrairement à ce que tu sembles croire, ton pire ennemi, ce n’est pas d’être oubliée, remplacée ou que je vienne à me lasser, non, ton pire ennemi c’est d’éteindre la flamme de l’espoir qui brûle en moi. Alors en affrontant tes propres démons, n’oublie pas qu’une lueur a jailli dans mon cœur il y a de ça presque un an et que si tu y tiens, tu dois la protéger." },
        { number: 4, title: '03 Juillet, 13h51', content: "3 jours. C'est à peu près le temps qu'il faut pour que tu commences à me manquer. J'veux dire, avant, je pense à toi, mais une fois ce délai passé, tu envahis mes pensées et mes émotions et à nouveau je me mets à romancer un futur à tes côtés. J'enverrai sûrement tout ça pour le 8, donc encore 5 jours. J'ai toujours cette appréhension de me demander comment tu réagis dans ces moments-là. J'crois que pour la science je vais devoir passer ma vie avec toi pour te comprendre hein, c'est comme ça, on y peut rien...<br />J'me pose aussi la question, est-ce qu'en plus d'une semaine je vais te manquer ou ton cerveau m'aura écarté de tes pensées ? Rahlala, j'crois que le jour où je te manquerai vraiment, je serai vraiment heureux de me dire que j'ai gagné une place suffisamment importante dans ton cœur. Accorde la moi et je te rendrai plus heureuse chaque jour qui passera." },
        { number: 5, title: '03 Juillet, 23h48', content: "Je mattais Black Lagoon quand m'est revenu en tête le fait que ça fait TROP LONGTEMPS qu'on a pas regardé Gintama. En fait, tu proposes de regarder un truc, tu choisis le truc le plus LONG et on avance pas parce que mademoiselle est une chieuse. C'est quoi le plan ? Tu veux que ça soit notre animé du soir quand on sera ensemble ? Faut pas être pressé avec toi bon dieu..." },
        { number: 6, title: '04 Juillet, 18h19', content: "Salut, il fait chaud, mettons nous nus et laissons nos corps se mélanger dans un intense moment entre passion et désir.<br />Et ça y est je me suis perdu à imaginer tes courbes danser près de moi.<br />Bon j'ai pas eu le temps de checker ce matin, normalement la figurine est finie. J'espère que le rendu sera cool, sinon tu sauras jamais de quoi je parlais...<br />J'checkerai ça ce soir, faut aussi que je ponce la boîte, j'ai officiellement la flemme mais bon faut que le rendu soit le plus propre possible. Puis faut que je trouve d'autres trucs à faire, histoire de remplir le vide du carton. Malheureusement vu que tu regardes trop de trucs obscurs, c'est dur de trouver... M'enfiiin. Rdv à la prochaine entrée pour savoir (ou non) si tout s'est bien passé. À ce soir ! (Fin pour toi c'est le truc d'après, j'sais même pas comment je vais faire la mise en forme quel enfeeeeeer)." },
        { number: 7, title: '04 Juillet, 22h57', content: "Re, bon je viens de sortir de la douche après avoir passé deux heures à nettoyer le petit Ikalgo. J'suis plutôt content du résultat franchement, ça rend bien. Bon j'ai pas encore fini et il me reste en gros que vendredi puisque l'objectif c'est de faire partir le tour samedi pour arriver lundi. Pfiouuuu et à tout ça s'ajoute le fait de coder un truc pour que toutes les entrées de journal soient accessibles via un papier QR dans la boîte. PFIOUUUU. Ouais je râle, j'm'inspire de toi, même si tu dirais que seule toi à ce droit.<br />Par contre va falloir m'aider, parce qu'après ça, j'aurai plus d'idées, va falloir que tu m'invites en vrai hein...<br />J'suis claqué bordel, j'espère que toi ça va, que tu passes une bonne semaine relaxation sans ma présence. Dès que tu auras reçu tout ça, j'ouvrirai à nouveau insta pour te faire chier t'en fais pas. Puis tes réactions me manquent, j'en viens à rêver mille et un scénario à tes côtés."},
        { number: 8, title: '05 Juillet, 00h55', content: "J'avais pas d'idée pour un dernier truc à faire quand soudain 4 lettres me sont apparues. Fnaf. Alors malheureusement j'ai pas de fil brun à disposition donc Freddy sera blanc mais bon au pire ça se peint et c'est toi qui a les compétences là-dessus pas moi.<br />On attend le résultat demain matin, en espérant que ça rende bien !<br />PS : J'sais pas si tu as essayé la bague (parce que mon cerveau de golem oui), mais vu que c'est un cadeau plus humoristique bien que je ne nie pas la symbolique derrière, elle est volontairement un peu plus grande qu'une vraie. Voilà annecdote finie, à demain !" },
        { number: 9, title: '05 Juillet, 19h58', content: "Bon. Je crois que j'ai réussi dans les temps. Je suis vraiment trop fort !<br>Le petit Freddy rend plutôt bien, j'suis content du modèle que j'ai choisi. Il va me rester à poncer les deux encore un peu et ça devrait le faire et le site rend bien.<br>AHHHHHHHHHHH JE SUIS STRESSÉ T'IMAGINES PAS, J'AI TOUJOURS CETTE APRÉHENSION A ME DIRE « ET SI ELLE TROUVE CA NAZE »  AHHHHHHHHHHHHH.<br> Normalement, tu recevras tout ça lundi, sinon c'est la faute de la poste.<br>Et si je me suis pas trompé, ça concordera avec tes résultats du bac donc RÉSULTATS ?????<br>Sinon tu me manques m'enfin l'objectif était de faire un gros truc d'un seul coup donc bon je pouvais pas t'écrire chaque jour, ça aurait tout gâché.<br>BREF, t'auras compris que je ne t'ai pas oubliée au contraire.<br>Allez je vais m'arrêter là, histoire de clore pour de bon ce dernier cadeau que je t'enverrai. <br>Bah oui le prochain tu l'auras IRL :)))) (j'ai déjà investi dans un bloc-notes pour écouter tout ce que tu diras aimer).<br>SUR CE, BONJOUR TRÉSOR, TU M'AS MANQUÉ, DÉPÊCHE DE M'ÉCRIRE SINON JE TE BOTTE PAS LE CUL (ouais nan parce que moi je veux le toucher ton cul nan mais)." },
        { number: 10, title: '06 Juillet, 15h32', content: "BON, cette entrée n'était pas censée exister mais j'ai reçu un mail me disant que le colis allait être livré mardi puis lundi. Donc c'est simple, si tu le reçois mardi je m'immole dans les locaux de la Poste pour avoir gâché tout l'effet que je me suis fait chier à donner + avoir loupé ton jour de résultats du bac (oui parce que bon, l'objecif c'était de tomber pile ce jour là, que tu te dises « Ohlala c'est incroyable j'accepte la demande en mariage ». DONC FAITES GAFFE LA POSTE. <br> Et si tu l'as reçu lundi, bah tout va biiien joie et bonne humeur !!! )" },
        { number: 11, title: '08 Juillet, 04h37', content: "Le timing du colis est à chier mais bon 🦔🧛. <br> Si jamais tu veux juste écrire un petit mot par rapport au colis ou te faire mousser pour tes résultats mais que flemme de lire insta, fais le via Discord. Dans tous les cas, Bisous Bisouus et prends pas trop ton temps sinon je continue Gintama sans toi <3" },
      ]
    }
  }
}
</script>

<style scoped>
.bg-header-color {
  background-color: rgba(124, 118, 206, 1);
}
</style>